### ISSUE TITLE
Make `way-sh` obsolete

### ISSUE THREAD

**Issue by b1rger** [ldelossa/way-shell#8]
I'm not sure if thats even possible, but it would be great if way-shell would not need a custom program for setting the volume or the brightness, but instead worked with the existing commands (like `wpctl` for wireplumber or `blight` for using the logind backlight).

**Comment by ldelossa** [comment]
It should! All those commands are for is to bridge into the API. 

The only small kicker is is when you use blight, we cant show "OSD" notifications. 

This is because I didnt want Way-Shell to "poll" the brightness file. 

Placing the brightness file in inotify/epoll I dont think is suggested, since its a virtual file and always returns readable once an event occurs.
